spring:
  jpa:
    open-in-view: false
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQL8Dialect
    hibernate:
      ddl-auto: validate
      default_batch_fetch_size: 100
    config:
      on-profile: local
  flyway:
    enabled: true
    baseline-on-migrate: true

parking:
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    jdbc-url: jdbc:mysql://localhost:3306/par_king
    username: root
    password: "test1234"
    read-only: false
    maximun-pool-size: 3
    minimun-pool-size: 2
    idle-timeout: 10000

redis:
  time-to-live: 3600
  cache-null-values: true
  host: localhost
  port: 6379
